### ISSUE TITLE
als-controller segfaults when getting status

### ISSUE THREAD

**Issue by christf** [danieleds/Asus-Zenbook-Ambient-Light-Sensor-Controller#21] opened 2015-11-06 22:25 UTC
running als-controller
then als-controller -e
then als-controller -s
will result in a segfault of the service process:
[29994.576229] als-controller[29781]: segfault at 7ff19934dfe0 ip 00007ff19b6da8ef sp 00007ff19934dfd0 error 6 in libc-2.21.so[7ff19b659000+1c0000]

**Comment by ElfoLiNk** [comment] 2015-11-10 16:41
I have the same error

**Comment by danieleds** [comment] 2016-01-23 10:55
OS, kernel version and Notebook model?

**Comment by danieleds** [comment] 2016-01-29 19:18
Closing as duplicate of #22

**Closed as completed by danieleds** 2016-01-29 19:18 UTC
